server:
  port: 8662

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fake-news-backend.eu.auth0.com/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: true

auth0:
  audience: https://backend-fakenews/api


