server:
  port: 8183

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:postgresql://ec2-34-247-118-233.eu-west-1.compute.amazonaws.com:5432/d8n5giebh3q56a
      username: cxuzadqckhmhvc
      password: c47dc5f3940ee3dec8d3a202c91ecb139b7f00d8651195c72952682bad9a5c9b
      driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      idle-timeout: 10000
      maximumPoolSize: 30
#spring:
#  database: h2
#  console: true
#  path: /h2
#  application:
#    name: user_service
#
#datasource:
#  platform: h2
#  url: jdbc:h2://localhost:8080/h2
#  username: sa
#  password: 1234
#  driverClassName: org.h2.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost



