package com.example.demo.utilities;

public enum ErrorCode {
    NOT_INIT,
    USERNAME_NOT_LONG_ENOUGH, USERNAME_NOT_MATCH_REGEX,
    PASSWORD_NO_LOWERCASE_LETTER, PASSWORD_NO_UPPERCASE_LETTER, PASSWORD_NO_NUMBER, PASSWORD_NO_SPECIAL_CHARACTER, PASSWORD_INVALID_CHARACTER, PASSWORD_NOT_LONG_ENOUGH,
    NO_ERRORS
}
